# Generated by Django 4.2.19 on 2025-02-28 00:29

from django.db import migrations, models
import django.db.models.deletion
import roomview.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Room',
            fields=[
                ('key', models.CharField(default=roomview.models.generate_slug, max_length=100, primary_key=True, serialize=False, unique=True)),
                ('name', models.TextField()),
            ],
            options={
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='roomview.room')),
            ],
            options={
                'verbose_name_plural': 'People',
            },
        ),
    ]
