# Generated by Django 4.2.7 on 2023-12-11 02:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_siteconfig'),
    ]

    operations = [
        migrations.AddField(
            model_name='solution',
            name='strategy',
            field=models.TextField(blank=True, null=True),
        ),
    ]
