# Generated by Django 4.2.7 on 2024-01-30 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_solution_strategy'),
    ]

    operations = [
        migrations.AddField(
            model_name='siteconfig',
            name='num',
            field=models.IntegerField(default=0),
        ),
    ]
