# Generated by Django 4.2.7 on 2024-01-30 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_siteconfig_num'),
    ]

    operations = [
        migrations.CreateModel(
            name='Site',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('room_desc', models.TextField(blank=True, null=True)),
                ('capacity', models.IntegerField(default=0)),
            ],
        ),
    ]
