# Generated by Django 4.2.7 on 2024-02-05 15:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_alter_site_room_desc'),
    ]

    operations = [
        migrations.CreateModel(
            name='Problem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rooms', models.TextField(blank=True, null=True)),
                ('students', models.ManyToManyField(related_name='problems', to='app.person')),
            ],
        ),
        migrations.AddField(
            model_name='solution',
            name='problem',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.problem'),
        ),
    ]
