# Generated by Django 4.2.10 on 2024-02-22 22:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_problem_solution_problem'),
    ]

    operations = [
        migrations.AddField(
            model_name='solution',
            name='capacities',
            field=models.TextField(default='{}'),
        ),
    ]
