# Generated by Django 4.2.7 on 2024-09-05 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_solution_capacities'),
    ]

    operations = [
        migrations.AddField(
            model_name='solution',
            name='tuned',
            field=models.BooleanField(default=False),
        ),
    ]
