# Generated by Django 4.2.19 on 2025-08-27 20:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_solution_tuned'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='solution',
            name='problem',
        ),
        migrations.AddField(
            model_name='solution',
            name='site',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='solutions', to='app.site'),
        ),
        migrations.DeleteModel(
            name='Problem',
        ),
    ]
