# Generated by Django 4.2.19 on 2025-08-27 20:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0013_remove_solution_problem_solution_site_delete_problem'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='solution',
            name='capacities',
        ),
        migrations.RemoveField(
            model_name='solution',
            name='solution',
        ),
        migrations.AddField(
            model_name='solution',
            name='gender',
            field=models.CharField(choices=[('male', 'Male'), ('female', 'Female'), ('nb', 'Non Binary')], default='nb', max_length=20),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('internal_name', models.TextField()),
                ('placed_name', models.TextField()),
                ('capacity', models.IntegerField()),
                ('highest_affinity_neighbor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='app.room')),
                ('people', models.ManyToManyField(related_name='+', to='app.person')),
                ('solution', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rooms', to='app.solution')),
            ],
        ),
    ]
