# Generated by Django 4.2.19 on 2025-09-01 02:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0014_remove_solution_capacities_remove_solution_solution_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='solution',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='children', to='app.solution'),
        ),
    ]
