# Generated by Django 4.2.19 on 2025-09-01 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0015_solution_parent'),
    ]

    operations = [
        migrations.AddField(
            model_name='solution',
            name='score',
            field=models.FloatField(default=-1),
        ),
    ]
