# Generated by Django 4.2.24 on 2026-03-13 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0016_solution_score'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='people',
            field=models.ManyToManyField(blank=True, null=True, related_name='+', to='app.person'),
        ),
        migrations.AlterField(
            model_name='room',
            name='placed_name',
            field=models.TextField(blank=True, null=True),
        ),
    ]
